
insert into MV_REBUILD_REF (SET_ID, MV_NAME, REFRESH_TYPE, ORDER_INDEX, IS_ATOMIC) VALUES (7,'MV_F_MREC_RECENT_FILE','FORCE',40,'N');
insert into MV_REBUILD_REF (SET_ID, MV_NAME, REFRESH_TYPE, ORDER_INDEX, IS_ATOMIC) VALUES (7,'MV_F_MREC_RECENT_TIME','FORCE',50,'N');
insert into MV_REBUILD_REF (SET_ID, MV_NAME, REFRESH_TYPE, ORDER_INDEX, IS_ATOMIC) VALUES (7,'MV_F_FILE_RECENT_SHORT','FORCE',60,'N');
insert into MV_REBUILD_REF (SET_ID, MV_NAME, REFRESH_TYPE, ORDER_INDEX, IS_ATOMIC) VALUES (7,'MV_F_FILE_RECENT_SHORT_2','FORCE',70,'N');
insert into MV_REBUILD_REF (SET_ID, MV_NAME, REFRESH_TYPE, ORDER_INDEX, IS_ATOMIC) VALUES (7,'MV_F_FILE_RECENT_SHORT_3','FORCE',80,'N');

exit;
