/*
 * Generated by asn1c-0.9.24 (http://lionet.info/asn1c)
 * From ASN.1 module "MSSR13"
 * 	found in "Ericsson_R13_hacked.asn1"
 */

#include "DataBlock.h"

static asn_TYPE_member_t asn_MBR_DataBlock_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DataBlock, choice.callDataRecord),
		-1 /* Ambiguous tag (CHOICE?) */,
		0,
		&asn_DEF_CallDataRecord,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"callDataRecord"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DataBlock, choice.padding),
		(ASN_TAG_CLASS_UNIVERSAL | (0 << 2)),
		0,
		&asn_DEF_Padding,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"padding"
		},
};
static asn_TYPE_tag2member_t asn_MAP_DataBlock_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (0 << 2)), 1, 0, 0 }, /* padding at 4 */
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uMTSGSMPLMNCallDataRecord at 9 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 } /* compositeCallDataRecord at 11 */
};
static asn_CHOICE_specifics_t asn_SPC_DataBlock_specs_1 = {
	sizeof(struct DataBlock),
	offsetof(struct DataBlock, _asn_ctx),
	offsetof(struct DataBlock, present),
	sizeof(((struct DataBlock *)0)->present),
	asn_MAP_DataBlock_tag2el_1,
	3,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_DataBlock = {
	"DataBlock",
	"DataBlock",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_DataBlock_1,
	2,	/* Elements count */
	&asn_SPC_DataBlock_specs_1	/* Additional specs */
};

