--Originally prepared for fresh install of VFI-UM (UM 6.0) taking up a total size of 20G
CREATE TABLESPACE ASCERTAIN_DATA
        DATAFILE '/data2/ORACLE/$ORACLE_SID/ascertain_dat_01.dbf' SIZE 200M
        AUTOEXTEND ON NEXT 1M MAXSIZE 500M
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE ASCERTAIN_IDX
        DATAFILE '/data2/ORACLE/$ORACLE_SID/ascertain_idx_01.dbf' SIZE 200M
        AUTOEXTEND ON NEXT 1M MAXSIZE 1G
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE IMM_DATA
		DATAFILE '/data2/ORACLE/$ORACLE_SID/imm_dat_01.dbf' SIZE 800M
		AUTOEXTEND ON NEXT 20M MAXSIZE 3G
		EXTENT MANAGEMENT LOCAL AUTOALLOCATE
		SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE IMM_IDX
		DATAFILE '/data2/ORACLE/$ORACLE_SID/imm_idx_01.dbf' SIZE 500M
		AUTOEXTEND ON NEXT 20M MAXSIZE 1G
		EXTENT MANAGEMENT LOCAL AUTOALLOCATE
		SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE CUSTOMER_DATA
        DATAFILE '/data2/ORACLE/$ORACLE_SID/customer_dat_01.dbf' SIZE 202M
        AUTOEXTEND ON NEXT 8M MAXSIZE 1G
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT MANUAL
/
CREATE TABLESPACE CUSTOMER_IDX
        DATAFILE '/data2/ORACLE/$ORACLE_SID/customer_idx_01.dbf' SIZE 202M
        AUTOEXTEND ON NEXT 8M MAXSIZE 500M
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT MANUAL
/
CREATE TABLESPACE UM_DWH_USG_DATA
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_dwh_usg_dat_01.dbf' SIZE 500M
        AUTOEXTEND ON NEXT 20M MAXSIZE 4G
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE UM_DWH_USG_IDX
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_dwh_usg_idx_01.dbf' SIZE 750M
        AUTOEXTEND ON NEXT 20M MAXSIZE 2G
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE UM_DWH_MTR_DATA
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_dwh_mtr_dat_01.dbf' SIZE 500M
        AUTOEXTEND ON NEXT 20M MAXSIZE 3500M
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE UM_DWH_MTR_IDX
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_dwh_mtr_idx_01.dbf' SIZE 750M
        AUTOEXTEND ON NEXT 20M MAXSIZE 2G
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE UM_MV_DATA
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_mv_dat_01.dbf' SIZE 200M
        AUTOEXTEND ON NEXT 20M MAXSIZE 500M
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE UM_MV_IDX
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_mv_idx_01.dbf' SIZE 200M
        AUTOEXTEND ON NEXT 20M MAXSIZE 500M
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
CREATE TABLESPACE UM_MVL_DATA
        DATAFILE '/data2/ORACLE/$ORACLE_SID/um_mvl_dat_01.dbf' SIZE 100M
        AUTOEXTEND ON NEXT 20M MAXSIZE 500M
        EXTENT MANAGEMENT LOCAL AUTOALLOCATE
        SEGMENT SPACE MANAGEMENT AUTO
/
exit;

