alter TABLE ATTRIBUTE_FILTER_CONF_REF drop constraint ATTRIBUTE_FILTER_CONF_REF_3_CK;

ALTER TABLE ATTRIBUTE_FILTER_CONF_REF
  ADD CONSTRAINT ATTRIBUTE_FILTER_CONF_REF_3_CK CHECK (FILTER_TYPE IN ('DATE','DATERANGE','DATETIME','DROPDOWN','MULTISELECT','FREETEXT','FREETEXT_REG'));
  

exit;
