echo "select * from GDL.SQL_REF where SQL_ID > 99999 ;" > sql/gdl/SQL_REF.sql                                                                         
echo "select * from GDL.SQL_REF where SQL_ID > 99999 ;" > sql/gdl/SQL_REF.sql                                                                         
echo "select * from GDL.LOADABLE_TABLES_REF where LOADABLE_TABLE_ID > 99999 ;" > sql/gdl/LOADABLE_TABLES_REF.sql                                      
echo "select * from GDL.FORMAT_MAPPING_VERSION where MAPPING_VERSION_ID > 99999 ;" > sql/gdl/FORMAT_MAPPING_VERSION.sql                               
echo "select * from GDL.FORMAT_MAPPING where MAPPING_ID > 99999 ;" > sql/gdl/FORMAT_MAPPING.sql                                                       
echo "select * from GDL.FORMAT_FIELD_TYPE_REF where FORMAT_FIELD_TYPE > 99999 ;" > sql/gdl/FORMAT_FIELD_TYPE_REF.sql                                  
echo "select * from GDL.FORMAT_FIELD_REF where FORMAT_FIELD_ID > 99999 ;" > sql/gdl/FORMAT_FIELD_REF.sql                                              
echo "select * from GDL.FMT_MAP_TRANSFER_JN where MAPPING_VERSION_ID > 99999 ;" > sql/gdl/FMT_MAP_TRANSFER_JN.sql                                     
echo "select * from GDL.FMT_MAP_TRANSFER_JN where TRANSFER_ID > 99999 ;" > sql/gdl/FMT_MAP_TRANSFER_JN.sql                                            
echo "select * from GDL.FMT_MAP_ACTION_TYPE_REF where ACTION_TYPE > 99999 ;" > sql/gdl/FMT_MAP_ACTION_TYPE_REF.sql                                    
echo "select * from GDL.FMT_MAP_ACTION_MAP where MAP_ACTION_MAP_ID > 99999 ;" > sql/gdl/FMT_MAP_ACTION_MAP.sql                                        
echo "select * from GDL.FIELD_MAPPING where MAPPING_VERSION_ID > 99999 ;" > sql/gdl/FIELD_MAPPING.sql                                                 
echo "select * from GDL.FIELD_MAPPING where TARGET_FIELD > 99999 ;" > sql/gdl/FIELD_MAPPING.sql                                                       
echo "select * from GDL.EX_TRANSFORM_VERSION_REF where TRANSFORM_VERSION_ID > 99999 ;" > sql/gdl/EX_TRANSFORM_VERSION_REF.sql                         
echo "select * from GDL.EX_TRANSFORM_REF where TRANSFORM_ID > 99999 ;" > sql/gdl/EX_TRANSFORM_REF.sql                                                 
echo "select * from GDL.EX_TRANSFORM_PROCESS_REF where PROCESS_ID > 99999 ;" > sql/gdl/EX_TRANSFORM_PROCESS_REF.sql                                   
echo "select * from GDL.EX_SEED_TRANSFORM_JN where SEED_ID > 99999 ;" > sql/gdl/EX_SEED_TRANSFORM_JN.sql                                              
echo "select * from GDL.EX_SEED_TRANSFORM_JN where TRANSFORM_ID > 99999 ;" > sql/gdl/EX_SEED_TRANSFORM_JN.sql                                         
echo "select * from GDL.EX_SEED_REF where SEED_ID > 99999 ;" > sql/gdl/EX_SEED_REF.sql                                                                
echo "select * from GDL.EX_CLASS_REF where CLASS_ID > 99999 ;" > sql/gdl/EX_CLASS_REF.sql                                                             
echo "select * from JOBS.TRANSFER_TYPE_REF where TRANSFER_TYPE_ID > 99999 ;" > sql/jobs/TRANSFER_TYPE_REF.sql                                         
echo "select * from JOBS.TRANSFER_REF where TRANSFER_ID > 99999 ;" > sql/jobs/TRANSFER_REF.sql                                                        
echo "select * from JOBS.TERMINATION_LIST where JOB_ID > 99999 ;" > sql/jobs/TERMINATION_LIST.sql                                                     
echo "select * from JOBS.RETURN_CODE_REF where RETURN_CODE > 99999 ;" > sql/jobs/RETURN_CODE_REF.sql                                                  
